# Generated by Django 5.0.6 on 2024-06-29 06:47

import Articles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to=Articles.models.upload_to),
        ),
    ]
